name: CI/CD - Credit Risk API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run linting
        run: |
          black --check .
          flake8 . --max-line-length=100 --ignore=E203,W503

      - name: Run type checking
        run: mypy . --ignore-missing-imports

      - name: Run tests with coverage
        run: pytest -v --cov=app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  build-and-push-docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Hub push (keeps your public image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: thaitri2005/credit_scorecard_for_default_prediction:latest

      # Azure Container Registry push
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name creditscorecardwoeiv

      - name: Build and push image to ACR
        run: |
          docker build -t creditscorecardwoeiv.azurecr.io/credit-risk-api:latest .
          docker push creditscorecardwoeiv.azurecr.io/credit-risk-api:latest

      # Deploy to Azure Web App for Containers
      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name creditscorecardwoeiv \
            --resource-group docker-fastapi-credit-scorecard \
            --docker-custom-image-name creditscorecardwoeiv.azurecr.io/credit-risk-api:latest \
            --docker-registry-server-url https://creditscorecardwoeiv.azurecr.io

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t credit-risk-api:test .

      - name: Run Trivy (SARIF output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: credit-risk-api:test
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  docker-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t credit-risk-api:test .

      - name: Run Trivy Docker image scan (table output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'credit-risk-api:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'